FROM node:20-bullseye-slim
WORKDIR /app

RUN apt-get update && apt-get install -y \
    openssl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY public ./public
COPY .next/standalone ./
COPY .next/static ./.next/static
COPY prisma ./prisma

EXPOSE 3000
CMD ["node", "server.js"]
